//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmercomDisp.Data.CallResponseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallResponseDto", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class CallResponseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArriveTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrigadeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinishTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncidentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransferTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArriveTime {
            get {
                return this.ArriveTimeField;
            }
            set {
                if ((this.ArriveTimeField.Equals(value) != true)) {
                    this.ArriveTimeField = value;
                    this.RaisePropertyChanged("ArriveTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrigadeName {
            get {
                return this.BrigadeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrigadeNameField, value) != true)) {
                    this.BrigadeNameField = value;
                    this.RaisePropertyChanged("BrigadeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FinishTime {
            get {
                return this.FinishTimeField;
            }
            set {
                if ((this.FinishTimeField.Equals(value) != true)) {
                    this.FinishTimeField = value;
                    this.RaisePropertyChanged("FinishTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncidentId {
            get {
                return this.IncidentIdField;
            }
            set {
                if ((this.IncidentIdField.Equals(value) != true)) {
                    this.IncidentIdField = value;
                    this.RaisePropertyChanged("IncidentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnTime {
            get {
                return this.ReturnTimeField;
            }
            set {
                if ((this.ReturnTimeField.Equals(value) != true)) {
                    this.ReturnTimeField = value;
                    this.RaisePropertyChanged("ReturnTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransferTime {
            get {
                return this.TransferTimeField;
            }
            set {
                if ((this.TransferTimeField.Equals(value) != true)) {
                    this.TransferTimeField = value;
                    this.RaisePropertyChanged("TransferTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class ConnectionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CallResponseService.ICallResponseService")]
    public interface ICallResponseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/GetCallResponsesForCall", ReplyAction="http://tempuri.org/ICallResponseService/GetCallResponsesForCallResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.CallResponseService.ConnectionFault), Action="http://tempuri.org/ICallResponseService/GetCallResponsesForCallConnectionFaultFau" +
            "lt", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        EmercomDisp.Data.CallResponseService.CallResponseDto[] GetCallResponsesForCall(int callId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/GetCallResponsesForCall", ReplyAction="http://tempuri.org/ICallResponseService/GetCallResponsesForCallResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.CallResponseService.CallResponseDto[]> GetCallResponsesForCallAsync(int callId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/GetCallResponseById", ReplyAction="http://tempuri.org/ICallResponseService/GetCallResponseByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.CallResponseService.ConnectionFault), Action="http://tempuri.org/ICallResponseService/GetCallResponseByIdConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        EmercomDisp.Data.CallResponseService.CallResponseDto GetCallResponseById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/GetCallResponseById", ReplyAction="http://tempuri.org/ICallResponseService/GetCallResponseByIdResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.CallResponseService.CallResponseDto> GetCallResponseByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/UpdateCallResponse", ReplyAction="http://tempuri.org/ICallResponseService/UpdateCallResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.CallResponseService.ConnectionFault), Action="http://tempuri.org/ICallResponseService/UpdateCallResponseConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void UpdateCallResponse(EmercomDisp.Data.CallResponseService.CallResponseDto callResponse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/UpdateCallResponse", ReplyAction="http://tempuri.org/ICallResponseService/UpdateCallResponseResponse")]
        System.Threading.Tasks.Task UpdateCallResponseAsync(EmercomDisp.Data.CallResponseService.CallResponseDto callResponse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/DeleteCallResponse", ReplyAction="http://tempuri.org/ICallResponseService/DeleteCallResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.CallResponseService.ConnectionFault), Action="http://tempuri.org/ICallResponseService/DeleteCallResponseConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void DeleteCallResponse(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallResponseService/DeleteCallResponse", ReplyAction="http://tempuri.org/ICallResponseService/DeleteCallResponseResponse")]
        System.Threading.Tasks.Task DeleteCallResponseAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICallResponseServiceChannel : EmercomDisp.Data.CallResponseService.ICallResponseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallResponseServiceClient : System.ServiceModel.ClientBase<EmercomDisp.Data.CallResponseService.ICallResponseService>, EmercomDisp.Data.CallResponseService.ICallResponseService {
        
        public CallResponseServiceClient() {
        }
        
        public CallResponseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallResponseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallResponseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallResponseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmercomDisp.Data.CallResponseService.CallResponseDto[] GetCallResponsesForCall(int callId) {
            return base.Channel.GetCallResponsesForCall(callId);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.CallResponseService.CallResponseDto[]> GetCallResponsesForCallAsync(int callId) {
            return base.Channel.GetCallResponsesForCallAsync(callId);
        }
        
        public EmercomDisp.Data.CallResponseService.CallResponseDto GetCallResponseById(int id) {
            return base.Channel.GetCallResponseById(id);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.CallResponseService.CallResponseDto> GetCallResponseByIdAsync(int id) {
            return base.Channel.GetCallResponseByIdAsync(id);
        }
        
        public void UpdateCallResponse(EmercomDisp.Data.CallResponseService.CallResponseDto callResponse) {
            base.Channel.UpdateCallResponse(callResponse);
        }
        
        public System.Threading.Tasks.Task UpdateCallResponseAsync(EmercomDisp.Data.CallResponseService.CallResponseDto callResponse) {
            return base.Channel.UpdateCallResponseAsync(callResponse);
        }
        
        public void DeleteCallResponse(int id) {
            base.Channel.DeleteCallResponse(id);
        }
        
        public System.Threading.Tasks.Task DeleteCallResponseAsync(int id) {
            return base.Channel.DeleteCallResponseAsync(id);
        }
    }
}
