//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmercomDisp.Data.BrigadeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrigadeDto", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class BrigadeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnCall {
            get {
                return this.IsOnCallField;
            }
            set {
                if ((this.IsOnCallField.Equals(value) != true)) {
                    this.IsOnCallField = value;
                    this.RaisePropertyChanged("IsOnCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberCount {
            get {
                return this.MemberCountField;
            }
            set {
                if ((this.MemberCountField.Equals(value) != true)) {
                    this.MemberCountField = value;
                    this.RaisePropertyChanged("MemberCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class ConnectionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class SqlFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrigadeMemberDto", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class BrigadeMemberDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrigadeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrigadeName {
            get {
                return this.BrigadeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrigadeNameField, value) != true)) {
                    this.BrigadeNameField = value;
                    this.RaisePropertyChanged("BrigadeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class ArgumentFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrigadeService.IBrigadeService")]
    public interface IBrigadeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeById", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeByIdConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeByIdSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        EmercomDisp.Data.BrigadeService.BrigadeDto GetBrigadeById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeById", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeByIdResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeDto> GetBrigadeByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigades", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/GetBrigadesConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/GetBrigadesSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        EmercomDisp.Data.BrigadeService.BrigadeDto[] GetBrigades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigades", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadesResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeDto[]> GetBrigadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeMembers", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeMembersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeMembersConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeMembersSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        EmercomDisp.Data.BrigadeService.BrigadeMemberDto[] GetBrigadeMembers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeMembers", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeMembersResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeMemberDto[]> GetBrigadeMembersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeMembersByBrigadeId", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeMembersByBrigadeIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeMembersByBrigadeIdConnectionFaultFau" +
            "lt", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeMembersByBrigadeIdSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        EmercomDisp.Data.BrigadeService.BrigadeMemberDto[] GetBrigadeMembersByBrigadeId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeMembersByBrigadeId", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeMembersByBrigadeIdResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeMemberDto[]> GetBrigadeMembersByBrigadeIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/UpdateBrigade", ReplyAction="http://tempuri.org/IBrigadeService/UpdateBrigadeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/UpdateBrigadeConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/UpdateBrigadeSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ArgumentFault), Action="http://tempuri.org/IBrigadeService/UpdateBrigadeArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void UpdateBrigade(EmercomDisp.Data.BrigadeService.BrigadeDto brigade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/UpdateBrigade", ReplyAction="http://tempuri.org/IBrigadeService/UpdateBrigadeResponse")]
        System.Threading.Tasks.Task UpdateBrigadeAsync(EmercomDisp.Data.BrigadeService.BrigadeDto brigade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/CreateBrigade", ReplyAction="http://tempuri.org/IBrigadeService/CreateBrigadeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/CreateBrigadeConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/CreateBrigadeSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ArgumentFault), Action="http://tempuri.org/IBrigadeService/CreateBrigadeArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void CreateBrigade(EmercomDisp.Data.BrigadeService.BrigadeDto brigade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/CreateBrigade", ReplyAction="http://tempuri.org/IBrigadeService/CreateBrigadeResponse")]
        System.Threading.Tasks.Task CreateBrigadeAsync(EmercomDisp.Data.BrigadeService.BrigadeDto brigade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/DeleteBrigade", ReplyAction="http://tempuri.org/IBrigadeService/DeleteBrigadeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/DeleteBrigadeConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/DeleteBrigadeSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void DeleteBrigade(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/DeleteBrigade", ReplyAction="http://tempuri.org/IBrigadeService/DeleteBrigadeResponse")]
        System.Threading.Tasks.Task DeleteBrigadeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeMemberById", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeMemberByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeMemberByIdConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/GetBrigadeMemberByIdSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        EmercomDisp.Data.BrigadeService.BrigadeMemberDto GetBrigadeMemberById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/GetBrigadeMemberById", ReplyAction="http://tempuri.org/IBrigadeService/GetBrigadeMemberByIdResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeMemberDto> GetBrigadeMemberByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/UpdateBrigadeMember", ReplyAction="http://tempuri.org/IBrigadeService/UpdateBrigadeMemberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/UpdateBrigadeMemberConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/UpdateBrigadeMemberSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ArgumentFault), Action="http://tempuri.org/IBrigadeService/UpdateBrigadeMemberArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void UpdateBrigadeMember(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/UpdateBrigadeMember", ReplyAction="http://tempuri.org/IBrigadeService/UpdateBrigadeMemberResponse")]
        System.Threading.Tasks.Task UpdateBrigadeMemberAsync(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/DeleteBrigadeMember", ReplyAction="http://tempuri.org/IBrigadeService/DeleteBrigadeMemberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/DeleteBrigadeMemberConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/DeleteBrigadeMemberSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void DeleteBrigadeMember(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/DeleteBrigadeMember", ReplyAction="http://tempuri.org/IBrigadeService/DeleteBrigadeMemberResponse")]
        System.Threading.Tasks.Task DeleteBrigadeMemberAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/CreateBrigadeMember", ReplyAction="http://tempuri.org/IBrigadeService/CreateBrigadeMemberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ConnectionFault), Action="http://tempuri.org/IBrigadeService/CreateBrigadeMemberConnectionFaultFault", Name="ConnectionFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.SqlFault), Action="http://tempuri.org/IBrigadeService/CreateBrigadeMemberSqlFaultFault", Name="SqlFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmercomDisp.Data.BrigadeService.ArgumentFault), Action="http://tempuri.org/IBrigadeService/CreateBrigadeMemberArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
        void CreateBrigadeMember(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeService/CreateBrigadeMember", ReplyAction="http://tempuri.org/IBrigadeService/CreateBrigadeMemberResponse")]
        System.Threading.Tasks.Task CreateBrigadeMemberAsync(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrigadeServiceChannel : EmercomDisp.Data.BrigadeService.IBrigadeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrigadeServiceClient : System.ServiceModel.ClientBase<EmercomDisp.Data.BrigadeService.IBrigadeService>, EmercomDisp.Data.BrigadeService.IBrigadeService {
        
        public BrigadeServiceClient() {
        }
        
        public BrigadeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrigadeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrigadeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrigadeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmercomDisp.Data.BrigadeService.BrigadeDto GetBrigadeById(int id) {
            return base.Channel.GetBrigadeById(id);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeDto> GetBrigadeByIdAsync(int id) {
            return base.Channel.GetBrigadeByIdAsync(id);
        }
        
        public EmercomDisp.Data.BrigadeService.BrigadeDto[] GetBrigades() {
            return base.Channel.GetBrigades();
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeDto[]> GetBrigadesAsync() {
            return base.Channel.GetBrigadesAsync();
        }
        
        public EmercomDisp.Data.BrigadeService.BrigadeMemberDto[] GetBrigadeMembers() {
            return base.Channel.GetBrigadeMembers();
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeMemberDto[]> GetBrigadeMembersAsync() {
            return base.Channel.GetBrigadeMembersAsync();
        }
        
        public EmercomDisp.Data.BrigadeService.BrigadeMemberDto[] GetBrigadeMembersByBrigadeId(int id) {
            return base.Channel.GetBrigadeMembersByBrigadeId(id);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeMemberDto[]> GetBrigadeMembersByBrigadeIdAsync(int id) {
            return base.Channel.GetBrigadeMembersByBrigadeIdAsync(id);
        }
        
        public void UpdateBrigade(EmercomDisp.Data.BrigadeService.BrigadeDto brigade) {
            base.Channel.UpdateBrigade(brigade);
        }
        
        public System.Threading.Tasks.Task UpdateBrigadeAsync(EmercomDisp.Data.BrigadeService.BrigadeDto brigade) {
            return base.Channel.UpdateBrigadeAsync(brigade);
        }
        
        public void CreateBrigade(EmercomDisp.Data.BrigadeService.BrigadeDto brigade) {
            base.Channel.CreateBrigade(brigade);
        }
        
        public System.Threading.Tasks.Task CreateBrigadeAsync(EmercomDisp.Data.BrigadeService.BrigadeDto brigade) {
            return base.Channel.CreateBrigadeAsync(brigade);
        }
        
        public void DeleteBrigade(int id) {
            base.Channel.DeleteBrigade(id);
        }
        
        public System.Threading.Tasks.Task DeleteBrigadeAsync(int id) {
            return base.Channel.DeleteBrigadeAsync(id);
        }
        
        public EmercomDisp.Data.BrigadeService.BrigadeMemberDto GetBrigadeMemberById(int id) {
            return base.Channel.GetBrigadeMemberById(id);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.BrigadeService.BrigadeMemberDto> GetBrigadeMemberByIdAsync(int id) {
            return base.Channel.GetBrigadeMemberByIdAsync(id);
        }
        
        public void UpdateBrigadeMember(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember) {
            base.Channel.UpdateBrigadeMember(brigadeMember);
        }
        
        public System.Threading.Tasks.Task UpdateBrigadeMemberAsync(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember) {
            return base.Channel.UpdateBrigadeMemberAsync(brigadeMember);
        }
        
        public void DeleteBrigadeMember(int id) {
            base.Channel.DeleteBrigadeMember(id);
        }
        
        public System.Threading.Tasks.Task DeleteBrigadeMemberAsync(int id) {
            return base.Channel.DeleteBrigadeMemberAsync(id);
        }
        
        public void CreateBrigadeMember(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember) {
            base.Channel.CreateBrigadeMember(brigadeMember);
        }
        
        public System.Threading.Tasks.Task CreateBrigadeMemberAsync(EmercomDisp.Data.BrigadeService.BrigadeMemberDto brigadeMember) {
            return base.Channel.CreateBrigadeMemberAsync(brigadeMember);
        }
    }
}
