//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmercomDisp.Data.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallDto", Namespace="http://schemas.datacontract.org/2004/07/EmercomDisp.Service.Dto.Models")]
    [System.SerializableAttribute()]
    public partial class CallDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CallTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CallTime {
            get {
                return this.CallTimeField;
            }
            set {
                if ((this.CallTimeField.Equals(value) != true)) {
                    this.CallTimeField = value;
                    this.RaisePropertyChanged("CallTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICallService")]
    public interface ICallService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCalls", ReplyAction="http://tempuri.org/ICallService/GetCallsResponse")]
        EmercomDisp.Data.ServiceReference1.CallDto[] GetCalls();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCalls", ReplyAction="http://tempuri.org/ICallService/GetCallsResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.ServiceReference1.CallDto[]> GetCallsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallsByCategory", ReplyAction="http://tempuri.org/ICallService/GetCallsByCategoryResponse")]
        EmercomDisp.Data.ServiceReference1.CallDto[] GetCallsByCategory(string urgency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallsByCategory", ReplyAction="http://tempuri.org/ICallService/GetCallsByCategoryResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.ServiceReference1.CallDto[]> GetCallsByCategoryAsync(string urgency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallById", ReplyAction="http://tempuri.org/ICallService/GetCallByIdResponse")]
        EmercomDisp.Data.ServiceReference1.CallDto GetCallById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallById", ReplyAction="http://tempuri.org/ICallService/GetCallByIdResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Data.ServiceReference1.CallDto> GetCallByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCategories", ReplyAction="http://tempuri.org/ICallService/GetCategoriesResponse")]
        string[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCategories", ReplyAction="http://tempuri.org/ICallService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICallServiceChannel : EmercomDisp.Data.ServiceReference1.ICallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallServiceClient : System.ServiceModel.ClientBase<EmercomDisp.Data.ServiceReference1.ICallService>, EmercomDisp.Data.ServiceReference1.ICallService {
        
        public CallServiceClient() {
        }
        
        public CallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmercomDisp.Data.ServiceReference1.CallDto[] GetCalls() {
            return base.Channel.GetCalls();
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.ServiceReference1.CallDto[]> GetCallsAsync() {
            return base.Channel.GetCallsAsync();
        }
        
        public EmercomDisp.Data.ServiceReference1.CallDto[] GetCallsByCategory(string urgency) {
            return base.Channel.GetCallsByCategory(urgency);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.ServiceReference1.CallDto[]> GetCallsByCategoryAsync(string urgency) {
            return base.Channel.GetCallsByCategoryAsync(urgency);
        }
        
        public EmercomDisp.Data.ServiceReference1.CallDto GetCallById(int id) {
            return base.Channel.GetCallById(id);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Data.ServiceReference1.CallDto> GetCallByIdAsync(int id) {
            return base.Channel.GetCallByIdAsync(id);
        }
        
        public string[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
    }
}
