//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmercomDisp.Data.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICallService")]
    public interface ICallService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCalls", ReplyAction="http://tempuri.org/ICallService/GetCallsResponse")]
        EmercomDisp.Model.Models.Call[] GetCalls();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCalls", ReplyAction="http://tempuri.org/ICallService/GetCallsResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Model.Models.Call[]> GetCallsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallsByUrgency", ReplyAction="http://tempuri.org/ICallService/GetCallsByUrgencyResponse")]
        EmercomDisp.Model.Models.Call[] GetCallsByUrgency(string urgency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallsByUrgency", ReplyAction="http://tempuri.org/ICallService/GetCallsByUrgencyResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Model.Models.Call[]> GetCallsByUrgencyAsync(string urgency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallById", ReplyAction="http://tempuri.org/ICallService/GetCallByIdResponse")]
        EmercomDisp.Model.Models.Call GetCallById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCallById", ReplyAction="http://tempuri.org/ICallService/GetCallByIdResponse")]
        System.Threading.Tasks.Task<EmercomDisp.Model.Models.Call> GetCallByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCategories", ReplyAction="http://tempuri.org/ICallService/GetCategoriesResponse")]
        string[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallService/GetCategories", ReplyAction="http://tempuri.org/ICallService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICallServiceChannel : EmercomDisp.Data.ServiceReference1.ICallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallServiceClient : System.ServiceModel.ClientBase<EmercomDisp.Data.ServiceReference1.ICallService>, EmercomDisp.Data.ServiceReference1.ICallService {
        
        public CallServiceClient() {
        }
        
        public CallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmercomDisp.Model.Models.Call[] GetCalls() {
            return base.Channel.GetCalls();
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Model.Models.Call[]> GetCallsAsync() {
            return base.Channel.GetCallsAsync();
        }
        
        public EmercomDisp.Model.Models.Call[] GetCallsByUrgency(string urgency) {
            return base.Channel.GetCallsByUrgency(urgency);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Model.Models.Call[]> GetCallsByUrgencyAsync(string urgency) {
            return base.Channel.GetCallsByUrgencyAsync(urgency);
        }
        
        public EmercomDisp.Model.Models.Call GetCallById(int id) {
            return base.Channel.GetCallById(id);
        }
        
        public System.Threading.Tasks.Task<EmercomDisp.Model.Models.Call> GetCallByIdAsync(int id) {
            return base.Channel.GetCallByIdAsync(id);
        }
        
        public string[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
    }
}
